apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release-api.fullname" . }}
  labels:
    {{- include "release-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SAMPLE_API_TOKEN: {{ .Values.secretEnv.SAMPLE_API_TOKEN | quote }}

